#!/usr/bin/env python3
"""
Adaptive VASP launcher with dynamic memory optimization.

This script analyzes structure properties (atoms, k-points, memory requirements)
and automatically adjusts VASP parameters (NCORE, KPAR) based on available GPU memory
to avoid OOM errors while maintaining computational efficiency.

Usage:
    python adaptive_vasp_launcher.py <structure_dir> [--ngpu 1|2|4] [--max-nodes 4]
    
Example:
    python adaptive_vasp_launcher.py struct_0011 --ngpu 4 --max-nodes 4
    python adaptive_vasp_launcher.py struct_0050 --ngpu 2
"""

import os
import sys
import subprocess
import argparse
import json
from pathlib import Path
from datetime import datetime

class AdaptiveVASPLauncher:
    """Analyzes structure and optimizes VASP parameters for GPU execution."""
    
    def __init__(self, struct_dir, ngpu=4, max_nodes=4):
        """
        Initialize launcher with structure directory and GPU configuration.
        
        Args:
            struct_dir: Path to structure directory (contains POSCAR, INCAR, KPOINTS)
            ngpu: Number of GPUs to use (1, 2, or 4)
            max_nodes: Maximum number of nodes to request (default 4)
        """
        self.struct_dir = Path(struct_dir).resolve()
        self.ngpu = ngpu
        self.max_nodes = max_nodes
        self.struct_name = self.struct_dir.name
        self.log_file = self.struct_dir / "ADAPTIVE_OPTIMIZATION.log"
        self.config_file = self.struct_dir / "optimization_config.json"
        
        # Validate structure directory
        if not self.struct_dir.exists():
            raise FileNotFoundError(f"Structure directory not found: {self.struct_dir}")
        
        # Check required files
        self.required_files = ['POSCAR', 'INCAR', 'POTCAR']
        for fname in self.required_files:
            if not (self.struct_dir / fname).exists():
                raise FileNotFoundError(f"Missing {fname} in {self.struct_dir}")
        
        # Note: KPOINTS file is NOT required - k-point grid is auto-generated by VASP using KSPACING
        
        # Initialize optimization parameters
        self.optimization = {
            'struct_name': self.struct_name,
            'timestamp': datetime.now().isoformat(),
            'ngpu': ngpu,
            'max_nodes': max_nodes,
            'n_atoms': None,
            'n_kpoints_irreducible': None,
            'available_gpu_memory_mb': None,
            'optimization_strategy': None,
            'final_ncore': 8,
            'final_kpar': ngpu,
            'final_npar': None,
            'estimated_memory_per_gpu_gb': None,
            'reasoning': []
        }
    
    def log(self, message):
        """Write message to both console and log file."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_msg = f"[{timestamp}] {message}"
        print(log_msg)
        with open(self.log_file, 'a') as f:
            f.write(log_msg + '\n')
    
    def parse_poscar(self):
        """Extract number of atoms from POSCAR."""
        with open(self.struct_dir / 'POSCAR', 'r') as f:
            lines = f.readlines()
        
        # Line 0: comment, Line 1: scale, Lines 2-4: lattice vectors
        # Line 5: element symbols, Line 6: atom counts
        element_counts = lines[6].strip().split()
        n_atoms = sum(int(count) for count in element_counts)
        
        self.optimization['n_atoms'] = n_atoms
        self.log(f"Parsed POSCAR: {n_atoms} atoms")
        return n_atoms
    
    def parse_kpoints(self):
        """
        Calculate k-point grid from KSPACING in INCAR and lattice parameters.
        
        KSPACING controls k-point density in reciprocal space.
        Grid = max(1, round(2*pi / (KSPACING * lattice_vector_length)))
        """
        import math
        
        # Read lattice vectors from POSCAR
        with open(self.struct_dir / 'POSCAR', 'r') as f:
            lines = f.readlines()
        
        scale = float(lines[1].strip())
        lattice = []
        for i in range(2, 5):
            vec = [float(x) for x in lines[i].strip().split()]
            # Scale the lattice vector
            vec = [v * scale for v in vec]
            lattice.append(vec)
        
        # Read KSPACING from INCAR
        kspacing = 0.22  # Default
        with open(self.struct_dir / 'INCAR', 'r') as f:
            for line in f:
                if 'KSPACING' in line and '=' in line:
                    try:
                        kspacing = float(line.split('=')[1].split('#')[0].strip())
                        break
                    except ValueError:
                        pass
        
        # Calculate k-point grid based on KSPACING
        # Grid_i = max(1, round(2*pi / (KSPACING * |lattice_vector_i|)))
        grid = []
        for vec in lattice:
            # Calculate length of lattice vector
            length = math.sqrt(sum(v**2 for v in vec))
            # Calculate k-points for this direction
            n_kpts = max(1, round(2 * math.pi / (kspacing * length)))
            grid.append(n_kpts)
        
        # Total k-points
        total_kpoints = grid[0] * grid[1] * grid[2]
        
        # Estimate irreducible k-points (Gamma-centered, rough 35% of total)
        # (More accurate for metallic systems with high symmetry)
        n_irr_estimated = max(1, int(total_kpoints * 0.35))
        
        self.optimization['n_kpoints_irreducible'] = n_irr_estimated
        self.log(f"Calculated k-point grid: {grid[0]}×{grid[1]}×{grid[2]} = {total_kpoints} total")
        self.log(f"  Estimated irreducible k-points: ~{n_irr_estimated}")
        self.log(f"  (Based on KSPACING={kspacing} and lattice vectors)")
        return n_irr_estimated
    
    def estimate_memory_requirement(self, n_atoms, n_kpoints):
        """
        Estimate memory required per GPU for VASP calculation.
        
        Rough formula:
        - K-point data: ~3-4 MB per irreducible k-point
        - Wavefunction: ~1-2 MB per k-point per band (with LWAVE=F reduces this)
        - Density: ~50-100 MB (with LAECHG=F reduces this)
        - Misc overhead: ~500 MB
        
        Args:
            n_atoms: Number of atoms in structure
            n_kpoints: Number of irreducible k-points
            
        Returns:
            Estimated memory in GB
        """
        # Base k-point data memory
        kpoint_memory_mb = n_kpoints * 4.0  # 4 MB per k-point base
        
        # Add atom-dependent overhead
        atom_memory_mb = n_atoms * 10.0  # ~10 MB per atom
        
        # Add fixed overhead
        fixed_overhead_mb = 500.0
        
        total_mb = kpoint_memory_mb + atom_memory_mb + fixed_overhead_mb
        total_gb = total_mb / 1024.0
        
        self.optimization['estimated_memory_per_gpu_gb'] = round(total_gb, 2)
        self.log(f"Estimated memory requirement: {total_gb:.2f} GB per GPU")
        return total_gb
    
    def get_available_gpu_memory(self):
        """Query available GPU memory using nvidia-smi."""
        try:
            result = subprocess.run(
                ['nvidia-smi', '--query-gpu=memory.free', '--format=csv,noheader,nounits'],
                capture_output=True,
                text=True,
                timeout=5
            )
            
            if result.returncode == 0:
                memories = [float(x.strip()) for x in result.stdout.strip().split('\n')]
                avg_memory_mb = sum(memories) / len(memories)
                avg_memory_gb = avg_memory_mb / 1024.0
                
                self.optimization['available_gpu_memory_mb'] = round(avg_memory_mb, 1)
                self.log(f"Available GPU memory: {avg_memory_gb:.2f} GB average")
                return avg_memory_gb
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self.log("WARNING: nvidia-smi not available, assuming 24 GB per GPU")
            self.optimization['available_gpu_memory_mb'] = 24576  # 24 GB
            return 24.0
        
        return 24.0
    
    def optimize_parameters(self):
        """
        Analyze structure and available resources, optimize NCORE/KPAR.
        
        Strategy:
        1. Parse structure (atoms, k-points)
        2. Estimate memory requirement
        3. Check available GPU memory
        4. Adjust NCORE to reduce per-core memory footprint
        5. Adjust KPAR if needed (but keeping it <= ngpu)
        6. Consider requesting more nodes if memory still critical
        """
        # Check if parameters are preset (skip our own optimization)
        if self.config_file.exists():
            try:
                with open(self.config_file, 'r') as f:
                    existing_config = json.load(f)
                if existing_config.get('skip_optimization', False):
                    self.log("="*70)
                    self.log(f"ADAPTIVE VASP OPTIMIZATION: {self.struct_name}")
                    self.log("="*70)
                    self.log("Parameters pre-optimized (skipping auto-optimization)")
                    # Read current INCAR to get preset values
                    incar_file = self.struct_dir / 'INCAR'
                    if incar_file.exists():
                        with open(incar_file, 'r') as f:
                            for line in f:
                                if line.strip().startswith('NCORE'):
                                    ncore = int(line.split('=')[1].strip())
                                    self.optimization['final_ncore'] = ncore
                                if line.strip().startswith('KPAR'):
                                    kpar = int(line.split('=')[1].strip())
                                    self.optimization['final_kpar'] = kpar
                    self.log(f"Final Parameters:")
                    self.log(f"  NCORE = {self.optimization['final_ncore']}")
                    self.log(f"  KPAR = {self.optimization['final_kpar']}")
                    self.log("="*70)
                    return
            except Exception:
                pass
        
        # Remove KPOINTS file if it exists - we use KSPACING instead
        kpoints_file = self.struct_dir / 'KPOINTS'
        if kpoints_file.exists():
            kpoints_file.unlink()
            self.log("Removed KPOINTS file (using KSPACING for auto k-point generation)")
        
        self.log("="*70)
        self.log(f"ADAPTIVE VASP OPTIMIZATION: {self.struct_name}")
        self.log("="*70)
        
        # Step 1: Parse structure
        n_atoms = self.parse_poscar()
        n_kpoints = self.parse_kpoints()
        
        # Step 2: Estimate memory requirement
        est_memory = self.estimate_memory_requirement(n_atoms, n_kpoints)
        
        # Step 3: Check available memory
        available_gb = self.get_available_gpu_memory()
        
        # Step 4: Optimize parameters
        self.log(f"\nOptimization Analysis:")
        self.log(f"  Structure: {n_atoms} atoms, ~{n_kpoints} irreducible k-points")
        self.log(f"  Estimated need: {est_memory:.2f} GB per GPU")
        self.log(f"  Available: {available_gb:.2f} GB per GPU")
        self.log(f"  GPUs configured: {self.ngpu}")
        
        # Baseline (conservative: NCORE=16, KPAR=2)
        self.optimization['final_ncore'] = 16
        self.optimization['final_kpar'] = max(1, self.ngpu // 2)  # KPAR=2 for 4 GPUs
        self.optimization['final_npar'] = None
        
        # Safety margin: use 70% of available GPU memory
        safe_memory_gb = available_gb * 0.7
        
        if est_memory > safe_memory_gb:
            self.log(f"\n⚠ Memory pressure detected: {est_memory:.2f} GB > {safe_memory_gb:.2f} GB")
            self.optimization['reasoning'].append("High memory requirement relative to GPU capacity")
            
            # Strategy 1: Increase NCORE to 16 (double parallelization within GPU)
            self.optimization['final_ncore'] = 16
            self.optimization['reasoning'].append("Increased NCORE to 16 for within-GPU parallelization")
            
            # Estimate 40% memory reduction with NCORE=16
            reduced_memory = est_memory * 0.6
            self.log(f"  → Set NCORE=16 (est. reduction: {reduced_memory:.2f} GB per GPU)")
            
            if reduced_memory > safe_memory_gb:
                self.log(f"⚠ Still tight: {reduced_memory:.2f} GB > {safe_memory_gb:.2f} GB")
                
                # Strategy 2: Reduce KPAR to distribute fewer k-points per GPU
                if self.ngpu > 1:
                    new_kpar = max(1, self.ngpu // 2)
                    self.optimization['final_kpar'] = new_kpar
                    self.optimization['reasoning'].append(f"Reduced KPAR to {new_kpar} to reduce k-points per GPU")
                    self.log(f"  → Also set KPAR={new_kpar} (fewer k-points per GPU)")
                    reduced_memory *= (self.ngpu / new_kpar) * 0.8
                    self.log(f"    Est. memory after KPAR adjustment: {reduced_memory:.2f} GB per GPU")
        else:
            self.optimization['reasoning'].append("Memory sufficient with baseline settings")
            self.log(f"\n✓ Memory OK: {est_memory:.2f} GB < {safe_memory_gb:.2f} GB")
            self.log(f"  → Using baseline: NCORE=8, KPAR={self.ngpu}")
        
        # Final validation
        if est_memory > available_gb * 0.9:
            self.optimization['reasoning'].append("CRITICAL: May require additional nodes")
            nodes_needed = min(
                self.max_nodes,
                2 + int((est_memory - available_gb) / available_gb)
            )
            if nodes_needed > 1:
                self.optimization['reasoning'].append(f"Consider requesting {nodes_needed} nodes")
                self.log(f"\n⚠ CRITICAL: Consider requesting {nodes_needed} nodes instead of 1")
        
        self.log(f"\nFinal Parameters:")
        self.log(f"  NCORE = {self.optimization['final_ncore']}")
        self.log(f"  KPAR = {self.optimization['final_kpar']}")
        if self.optimization['final_npar']:
            self.log(f"  NPAR = {self.optimization['final_npar']}")
        self.log("="*70 + "\n")
        
        return True
    
    def modify_incar(self):
        """Apply optimization by modifying INCAR file."""
        incar_path = self.struct_dir / 'INCAR'
        
        with open(incar_path, 'r') as f:
            lines = f.readlines()
        
        # Modify NCORE and KPAR
        modified = False
        output_lines = []
        
        for line in lines:
            if line.strip().startswith('NCORE'):
                output_lines.append(f"NCORE = {self.optimization['final_ncore']}\n")
                modified = True
                self.log(f"Modified INCAR: NCORE → {self.optimization['final_ncore']}")
            elif line.strip().startswith('KPAR'):
                output_lines.append(f"KPAR = {self.optimization['final_kpar']}\n")
                modified = True
                self.log(f"Modified INCAR: KPAR → {self.optimization['final_kpar']}")
            elif self.optimization['final_npar'] and line.strip().startswith('NPAR'):
                output_lines.append(f"NPAR = {self.optimization['final_npar']}\n")
                modified = True
                self.log(f"Modified INCAR: NPAR → {self.optimization['final_npar']}")
            else:
                output_lines.append(line)
        
        # Write modified INCAR
        with open(incar_path, 'w') as f:
            f.writelines(output_lines)
        
        self.log(f"INCAR updated in {self.struct_dir}")
    
    def save_config(self):
        """Save optimization configuration to JSON for reference."""
        with open(self.config_file, 'w') as f:
            json.dump(self.optimization, f, indent=2)
        self.log(f"Configuration saved to {self.config_file}")
    
    def run(self):
        """Execute full optimization workflow."""
        try:
            self.optimize_parameters()
            self.modify_incar()
            self.save_config()
            self.log(f"✓ Optimization complete for {self.struct_name}")
            return True
        except Exception as e:
            self.log(f"✗ ERROR: {e}")
            return False


def main():
    parser = argparse.ArgumentParser(
        description='Adaptive VASP launcher with dynamic memory optimization'
    )
    parser.add_argument('struct_dir', help='Path to structure directory')
    parser.add_argument('--ngpu', type=int, choices=[1, 2, 4], default=4,
                        help='Number of GPUs to use (default: 4)')
    parser.add_argument('--max-nodes', type=int, default=4,
                        help='Maximum nodes to request (default: 4)')
    
    args = parser.parse_args()
    
    try:
        launcher = AdaptiveVASPLauncher(args.struct_dir, ngpu=args.ngpu, max_nodes=args.max_nodes)
        success = launcher.run()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"FATAL ERROR: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
