"""Canonical VASP scientific backend primitives."""

from .backend import VaspBackend
from .failures import VaspFailureEvidence, classify_failure
from .inputs import (
    VaspInputContext,
    VaspInputIdentity,
    build_input_context,
    canonical_poscar_bytes,
    canonical_poscar_text,
    hash_incar_text,
    hash_potcar_bytes,
    inject_incar_defaults,
    read_identity,
    strip_resource_incar_params,
)
from .outputs import (
    ResolvedVaspOutput,
    VaspJobEvidence,
    VaspParseResult,
    VaspPerformanceEvidence,
    VaspRegistryEvidence,
    outcar_is_complete,
    parse_outcar,
    parse_outcar_result,
    parse_performance_evidence,
    parse_stress_from_outcar,
    parse_virial_from_outcar,
    resolve_verified_output,
)
from .recovery import (
    VaspRecoveryDecision,
    build_retry_levels_for_gpu,
    decide_retry,
    write_incar_resource_parameters,
)
from .registry import (
    VALID_VASP_STATUSES,
    VASP_REGISTRY_VERSION,
    completed_jobs_registry_path,
    get_nepflow_root,
    get_registry_entry,
    read_completed_registry,
    read_status,
    upsert_registry_entry,
    write_completed_registry,
    write_status,
)

__all__ = [
    "ResolvedVaspOutput",
    "VaspBackend",
    "VaspFailureEvidence",
    "VaspInputIdentity",
    "VaspJobEvidence",
    "VaspInputContext",
    "VaspParseResult",
    "VaspPerformanceEvidence",
    "VaspRegistryEvidence",
    "VaspRecoveryDecision",
    "VALID_VASP_STATUSES",
    "VASP_REGISTRY_VERSION",
    "build_retry_levels_for_gpu",
    "build_input_context",
    "canonical_poscar_bytes",
    "canonical_poscar_text",
    "classify_failure",
    "completed_jobs_registry_path",
    "decide_retry",
    "get_nepflow_root",
    "get_registry_entry",
    "hash_incar_text",
    "hash_potcar_bytes",
    "inject_incar_defaults",
    "outcar_is_complete",
    "parse_outcar",
    "parse_outcar_result",
    "parse_performance_evidence",
    "parse_stress_from_outcar",
    "parse_virial_from_outcar",
    "resolve_verified_output",
    "read_identity",
    "read_completed_registry",
    "read_status",
    "strip_resource_incar_params",
    "upsert_registry_entry",
    "write_completed_registry",
    "write_incar_resource_parameters",
    "write_status",
]
