"""Canonical typed configuration package for NEPFlow."""

from nepflow.errors import ConfigurationError

from .creation import (
    render_default_config,
    validate_project_identity,
    write_validated_config,
)
from .legacy import load_legacy_config, to_legacy_config
from .loader import (
    CANONICAL_CONFIG_NAME,
    canonical_config_path,
    find_config_path,
    load_config,
)
from .models import (
    ALL_SOURCES,
    CONFIG_SCHEMA_VERSION,
    DEFAULT_SOURCE_SCOPE,
    GENERATION_SOURCE_SCOPE_FIELDS,
    MAGNETIC_DEFECT_FAMILIES,
    SUPPORTED_CONFIGURATIONAL_SOURCES,
    SUPPORTED_SURFACE_MILLER_INDICES,
    CompositionConfig,
    DftRecoveryConfig,
    GenerationConfig,
    HpcConfig,
    MagnetismConfig,
    MaterialsProjectConfig,
    NepConfig,
    NepflowConfig,
    NepTrainingConfig,
    PathsConfig,
    ProjectConfig,
    RootConfig,
    SelectionConfig,
    SlurmConfig,
    SourceScope,
    ValidationConfig,
    VaspConfig,
)
from .validation import (
    identity,
    normalize_crystal_structures,
    normalize_element_list,
    normalize_optional_elements,
    normalize_required_elements,
    normalize_target_n_atoms,
    validate_config,
)

__all__ = [
    "CANONICAL_CONFIG_NAME",
    "ALL_SOURCES",
    "CONFIG_SCHEMA_VERSION",
    "ConfigurationError",
    "CompositionConfig",
    "DftRecoveryConfig",
    "DEFAULT_SOURCE_SCOPE",
    "GENERATION_SOURCE_SCOPE_FIELDS",
    "MAGNETIC_DEFECT_FAMILIES",
    "GenerationConfig",
    "HpcConfig",
    "MaterialsProjectConfig",
    "MagnetismConfig",
    "NepConfig",
    "NepTrainingConfig",
    "NepflowConfig",
    "PathsConfig",
    "ProjectConfig",
    "RootConfig",
    "SelectionConfig",
    "SlurmConfig",
    "SourceScope",
    "SUPPORTED_CONFIGURATIONAL_SOURCES",
    "SUPPORTED_SURFACE_MILLER_INDICES",
    "ValidationConfig",
    "VaspConfig",
    "canonical_config_path",
    "find_config_path",
    "load_config",
    "load_legacy_config",
    "normalize_crystal_structures",
    "normalize_element_list",
    "normalize_optional_elements",
    "normalize_required_elements",
    "normalize_target_n_atoms",
    "render_default_config",
    "to_legacy_config",
    "identity",
    "validate_config",
    "validate_project_identity",
    "write_validated_config",
]
