"""Domain records and scientific identities for NEPFlow."""

from .calculations import DftExecutionResources, DftResultArtifact
from .datasets import DatasetIdentity, SelectedDatasetMember, TrainingDatasetManifest
from .identities import (
    VALIDATION_RUN_IDENTITY_SCHEMA,
    ArtifactIdentity,
    DescriptorCacheIdentity,
    DftCalculationIdentity,
    ModelRunIdentity,
    StructureIdentity,
    ValidationRunIdentity,
    annotate_structure_id,
    annotate_structure_ids,
    calculate_structure_id,
    canonical_structure_text,
    normalise_dft_calculation_identity,
)
from .models import (
    ModelArtifactMetadata,
    ModelRunRecord,
    ValidationArtifactMetadata,
    ValidationRunRecord,
)
from .structures import GeneratedStructureRecord, StructureProvenance
from .units import (
    CARTESIAN_3X3_COMPONENT_ORDER,
    ENERGY_UNIT_EV,
    FORCE_UNIT_EV_PER_ANGSTROM,
    STRESS_UNIT_EV_PER_ANGSTROM3,
    STRESS_UNIT_KBAR,
    VIRIAL_CONVENTION_POSITIVE_COMPRESSION,
    VIRIAL_TENSOR_CONVENTION_CARTESIAN_3X3,
    VIRIAL_UNIT_EV,
    VOIGT_COMPONENT_ORDER,
    require_tensor_shape,
    stress_from_virial,
    stress_kbar_to_ev_per_angstrom3,
    virial_from_stress,
)

__all__ = [
    "ArtifactIdentity",
    "CARTESIAN_3X3_COMPONENT_ORDER",
    "DatasetIdentity",
    "DescriptorCacheIdentity",
    "DftCalculationIdentity",
    "DftExecutionResources",
    "DftResultArtifact",
    "ENERGY_UNIT_EV",
    "FORCE_UNIT_EV_PER_ANGSTROM",
    "GeneratedStructureRecord",
    "ModelArtifactMetadata",
    "ModelRunIdentity",
    "ModelRunRecord",
    "STRESS_UNIT_EV_PER_ANGSTROM3",
    "STRESS_UNIT_KBAR",
    "SelectedDatasetMember",
    "StructureIdentity",
    "StructureProvenance",
    "TrainingDatasetManifest",
    "VALIDATION_RUN_IDENTITY_SCHEMA",
    "VIRIAL_CONVENTION_POSITIVE_COMPRESSION",
    "VIRIAL_TENSOR_CONVENTION_CARTESIAN_3X3",
    "VIRIAL_UNIT_EV",
    "VOIGT_COMPONENT_ORDER",
    "ValidationArtifactMetadata",
    "ValidationRunIdentity",
    "ValidationRunRecord",
    "annotate_structure_id",
    "annotate_structure_ids",
    "calculate_structure_id",
    "canonical_structure_text",
    "normalise_dft_calculation_identity",
    "require_tensor_shape",
    "stress_from_virial",
    "stress_kbar_to_ev_per_angstrom3",
    "virial_from_stress",
]
