"""Model-independent information-entropy selection."""

from .bandwidth import (
    BandwidthCalibrationError,
    build_entropy_pool,
    calculate_bandwidths,
    calculate_frozen_bandwidths,
    calibrate_bandwidth,
    calibrate_entropy_bandwidth,
    candidate_weights,
    compute_frozen_bandwidths,
    derive_candidate_probabilities,
    freeze_bandwidths,
)
from .kernels import (
    LeaveOneOutObjective,
    NormalizedKernelColumn,
    SourceProgressCallback,
    evaluate_leave_one_out_objective,
    iter_normalized_kernel_columns,
    normalized_kernel_matrix,
    source_normalisers,
    wendland,
    wendland_kernel,
)
from .models import (
    BandwidthCalibrationResult,
    BandwidthResult,
    BandwidthSettings,
    CalibrationAttempt,
    CalibrationResult,
    CalibrationSettings,
    EntropyBandwidthSettings,
    EntropyPool,
    FrozenBandwidths,
    InformationEntropyConfig,
    KernelMetadata,
)
from .neighbours import (
    ExactNeighbourResult,
    NeighbourResult,
    compute_exact_neighbours,
    compute_kth_distinct_neighbour_radii,
    compute_kth_distinct_neighbours,
    compute_neighbours,
    exact_kth_distinct_neighbour_radii,
    kth_distinct_neighbour_radii,
)
from .selector import InformationEntropySelectionAlgorithm

__all__ = [
    "BandwidthCalibrationError",
    "BandwidthCalibrationResult",
    "BandwidthResult",
    "BandwidthSettings",
    "CalibrationAttempt",
    "CalibrationResult",
    "CalibrationSettings",
    "EntropyBandwidthSettings",
    "EntropyPool",
    "ExactNeighbourResult",
    "FrozenBandwidths",
    "InformationEntropyConfig",
    "InformationEntropySelectionAlgorithm",
    "KernelMetadata",
    "LeaveOneOutObjective",
    "NormalizedKernelColumn",
    "NeighbourResult",
    "SourceProgressCallback",
    "build_entropy_pool",
    "calculate_bandwidths",
    "calculate_frozen_bandwidths",
    "calibrate_bandwidth",
    "calibrate_entropy_bandwidth",
    "compute_exact_neighbours",
    "compute_frozen_bandwidths",
    "compute_kth_distinct_neighbour_radii",
    "compute_kth_distinct_neighbours",
    "compute_neighbours",
    "exact_kth_distinct_neighbour_radii",
    "candidate_weights",
    "derive_candidate_probabilities",
    "evaluate_leave_one_out_objective",
    "freeze_bandwidths",
    "iter_normalized_kernel_columns",
    "kth_distinct_neighbour_radii",
    "normalized_kernel_matrix",
    "source_normalisers",
    "wendland_kernel",
    "wendland",
]
