"""Prepare sub-stage: create VASP job folders and shared runner script."""

import re
import time
from configparser import ConfigParser
from pathlib import Path

import numpy as np
from ase.io import iread

from ._common import logger, write_status


# ==================================================================
# job folder preparation
# ==================================================================

def prepare_jobs(
    config: ConfigParser,
    vasp_config_dir: Path,
    selected_dir: Path,
    jobs_dir: Path,
    datasets: list[str],
) -> None:
    """Create POSCAR/POTCAR/INCAR per structure (skips if already done)."""
    first_struct = jobs_dir / datasets[0] / "struct_0000"
    if first_struct.exists() and (first_struct / "POSCAR").exists():
        logger.info("Job folders already prepared — skipping preparation")
        return

    logger.info("Running VASP job preparation")

    # Validate INCAR template
    incar_template = vasp_config_dir / "INCAR"
    if not incar_template.exists():
        raise FileNotFoundError(
            f"INCAR template not found at {incar_template}\n"
            f"Place your VASP INCAR file in: {vasp_config_dir}/"
        )
    logger.info(f"  INCAR template: {incar_template}")

    incar_text = incar_template.read_text(encoding="utf-8")
    incar_text = inject_incar_defaults(incar_text, config)

    # Discover all unique elements across all datasets
    all_elements: set[str] = set()
    for ds in datasets:
        xyz_path = selected_dir / f"{ds}.xyz"
        if not xyz_path.exists():
            raise FileNotFoundError(
                f"Selected structures not found at {xyz_path}\n"
                f"Run the 'select' stage first."
            )
        for atoms in iread(str(xyz_path), format="extxyz"):
            all_elements.update(atoms.get_chemical_symbols())

    sorted_elements = sorted(all_elements)
    logger.info(f"  Elements: {', '.join(sorted_elements)}")

    # Validate pseudopotentials
    missing = [
        f"POTCAR_{e}" for e in sorted_elements
        if not (vasp_config_dir / f"POTCAR_{e}").exists()
    ]
    if missing:
        raise FileNotFoundError(
            f"Missing pseudopotential files in {vasp_config_dir}/:\n"
            + "\n".join(f"  - {m}" for m in missing)
        )

    # Pre-read POTCAR data
    potcar_data: dict[str, bytes] = {}
    for elem in sorted_elements:
        potcar_data[elem] = (vasp_config_dir / f"POTCAR_{elem}").read_bytes()

    # Create job folders for each dataset (POSCAR/POTCAR/INCAR only)
    for ds in datasets:
        logger.info(f"  Preparing {ds} jobs")
        xyz_path = selected_dir / f"{ds}.xyz"
        ds_jobs_dir = jobs_dir / ds
        ds_jobs_dir.mkdir(parents=True, exist_ok=True)

        t0 = time.perf_counter()
        count = 0

        for i, atoms in enumerate(iread(str(xyz_path), format="extxyz")):
            struct_dir = ds_jobs_dir / f"struct_{i:04d}"
            struct_dir.mkdir(parents=True, exist_ok=True)

            write_poscar(atoms, struct_dir / "POSCAR")

            struct_elements = sorted(set(atoms.get_chemical_symbols()))
            with open(struct_dir / "POTCAR", "wb") as f:
                for elem in struct_elements:
                    f.write(potcar_data[elem])

            (struct_dir / "INCAR").write_text(incar_text, encoding="utf-8")
            write_status(struct_dir, status="pending", retry_level=0)

            count += 1
            if count % 100 == 0:
                logger.info(f"    {count} structures prepared...")

        elapsed = time.perf_counter() - t0
        logger.info(f"  {ds.capitalize()}: {count} jobs ({elapsed:.1f}s)")

    logger.info("Job preparation complete")


# ==================================================================
# shared VASP runner script (like adaptive_healing.sh)
# ==================================================================

def write_shared_vasp_script(
    vasp_dir: Path,
    slurm_header: str,
    vasp_command: str,
) -> None:
    """Write vasp/run_vasp.sh — VASP runner submitted per structure.

    Submitted for each structure via:
      sbatch --job-name=<name> --nodes=N --ntasks-per-node=G \\
             --gres=gpu:G run_vasp.sh <struct_dir>

    The launcher writes NCORE/KPAR into each structure's INCAR before
    submission (both for initial runs and OOM retries).  The script
    simply reads INCAR and runs VASP.  On OOM it writes a marker file
    and exits; the launcher detects this and handles escalation.
    """
    bash_cmd = vasp_command.replace("{ntasks}", "$TOTAL_RANKS")
    # Prevent OpenMPI hwloc binding errors when requesting < max GPUs
    if "mpirun" in bash_cmd and "--bind-to" not in bash_cmd:
        bash_cmd = bash_cmd.replace("mpirun", "mpirun --bind-to none", 1)

    body = r"""
# ============================================================================
# VASP RUNNER (generated by nepflow)
# ============================================================================
# Usage: sbatch --job-name=<name> --nodes=N --ntasks-per-node=G \
#              --gres=gpu:G run_vasp.sh <struct_dir>
#
# NCORE/KPAR are read from INCAR (written by the launcher before submission).
# On OOM the script writes a marker file; the launcher handles retry/escalation.

STRUCT_DIR="$1"
if [ -z "$STRUCT_DIR" ]; then
    echo "Usage: sbatch run_vasp.sh <struct_dir>"
    exit 1
fi

if [ ! -d "$STRUCT_DIR" ]; then
    echo "ERROR: Structure directory not found: $STRUCT_DIR"
    exit 1
fi

echo "=========================================================================="
echo "nepflow VASP Runner"
echo "=========================================================================="
echo "Structure: $STRUCT_DIR"
echo "Job Name:  $SLURM_JOB_NAME"
echo "Timestamp: $(date)"
echo "=========================================================================="

cd "$STRUCT_DIR" || exit 1

# Read NCORE/KPAR from INCAR (launcher writes correct values before submission)
NCORE_VAL=$(grep -i "^[[:space:]]*NCORE" INCAR | grep "=" | head -1 | sed 's/.*=//;s/#.*//' | xargs)
KPAR_VAL=$(grep -i "^[[:space:]]*KPAR" INCAR | grep "=" | head -1 | sed 's/.*=//;s/#.*//' | xargs)
[ -z "$NCORE_VAL" ] && NCORE_VAL=2
[ -z "$KPAR_VAL" ] && KPAR_VAL=1

NGPU=${SLURM_NTASKS_PER_NODE:-4}
NNODES=${SLURM_NNODES:-1}
TOTAL_RANKS=$((NNODES * NGPU))

echo ""
echo "NCORE=$NCORE_VAL  KPAR=$KPAR_VAL  Nodes=$NNODES  GPUs/node=$NGPU  Ranks=$TOTAL_RANKS"
echo "Command: __VASP_CMD__"
echo "=========================================================================="

VASP_LOG="${STRUCT_DIR}/vasp_output.log"
__VASP_CMD__ > "$VASP_LOG" 2>&1
VASP_EXIT=$?

echo ""
echo "VASP exit code: $VASP_EXIT"

if [ -f "${STRUCT_DIR}/OUTCAR" ]; then
    echo "OUTCAR: $(wc -l < "${STRUCT_DIR}/OUTCAR") lines"
fi

# ============================================================================
# OOM DETECTION
# ============================================================================
# On OOM: write marker file and exit. The launcher detects the marker,
# escalates parameters (GPU count, NCORE, KPAR), and resubmits.
if grep -q "oom_kill" "$VASP_LOG" 2>/dev/null || [ $VASP_EXIT -eq 137 ]; then
    echo ""
    echo "OOM detected! Writing marker for launcher to handle retry..."
    echo "1" > "$STRUCT_DIR/.vasp_oom_detected"
    exit 1
fi

# ============================================================================
# SUCCESS OR ERROR
# ============================================================================
if [ $VASP_EXIT -eq 0 ]; then
    echo "VASP completed successfully"
    rm -f CHG CHGCAR WAVECAR CONTCAR DOSCAR EIGENVAL PCDAT
    exit 0
else
    echo "VASP failed with exit code $VASP_EXIT (not OOM)"
    echo "Check $STRUCT_DIR/vasp_output.log for details"
    exit 1
fi
"""
    body = body.replace("__VASP_CMD__", bash_cmd)

    script = slurm_header.rstrip("\n") + "\n" + body

    vasp_dir.mkdir(parents=True, exist_ok=True)
    script_path = vasp_dir / "run_vasp.sh"
    script_path.write_text(script, encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | 0o755)
    logger.info(f"  Shared VASP script: {script_path}")


# ==================================================================
# POSCAR writing
# ==================================================================

def write_poscar(atoms, path: Path) -> None:
    """Write an ASE Atoms object as a VASP5 POSCAR with atoms grouped by element."""
    symbols = np.array(atoms.get_chemical_symbols())
    unique_elements = sorted(set(symbols))

    sorted_indices = []
    counts = []
    for elem in unique_elements:
        mask = symbols == elem
        indices = np.where(mask)[0]
        sorted_indices.extend(indices.tolist())
        counts.append(int(mask.sum()))

    cell = atoms.get_cell()
    frac_positions = atoms.get_scaled_positions()

    with open(path, "w", encoding="utf-8") as f:
        info = atoms.info if hasattr(atoms, "info") else {}
        comment = info.get("config_type", " ".join(unique_elements))
        f.write(f"{comment}\n")
        f.write("1.0\n")
        for row in cell:
            f.write(f"  {row[0]:20.14f}  {row[1]:20.14f}  {row[2]:20.14f}\n")
        f.write("  " + "  ".join(unique_elements) + "\n")
        f.write("  " + "  ".join(str(c) for c in counts) + "\n")
        f.write("Direct\n")
        for idx in sorted_indices:
            p = frac_positions[idx]
            f.write(f"  {p[0]:20.14f}  {p[1]:20.14f}  {p[2]:20.14f}\n")


# ==================================================================
# INCAR injection
# ==================================================================

def inject_incar_defaults(incar_text: str, config: ConfigParser) -> str:
    """Append KSPACING and KGAMMA to INCAR text if not already present."""
    lines = incar_text.rstrip("\n")

    has_kspacing = bool(re.search(r"^\s*KSPACING\s*=", incar_text, re.MULTILINE | re.IGNORECASE))
    has_kgamma = bool(re.search(r"^\s*KGAMMA\s*=", incar_text, re.MULTILINE | re.IGNORECASE))

    additions = []
    if not has_kspacing:
        kspacing = config.get("vasp", "kspacing", fallback="0.30")
        additions.append(f"KSPACING = {kspacing}")
    if not has_kgamma:
        kgamma = config.get("vasp", "kgamma", fallback=".TRUE.")
        additions.append(f"KGAMMA = {kgamma}")

    if additions:
        lines += "\n\n# --- Injected by nepflow (not in user template) ---\n"
        lines += "\n".join(additions) + "\n"
    else:
        lines += "\n"

    return lines
